[package]
name = "gantry_nanotec_canopen"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
oze-canopen = "0.1.0"
thiserror = "2.0.16"
tokio = { version = "1.47.1", features = ["sync", "tracing"] }
tracing = "0.1.41"
