[package]
name = "gantry_demo"
version = "0.1.0"
edition = "2024"

[dependencies]
oze-canopen = "0.1.0"
tokio = { version = "1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
